import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FirebaseError } from 'firebase/app';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { Store } from './store';
import { AdminAuthService } from './auth.service';

@Component({selector:'app-admin-login',imports:[FormsModule,ButtonModule,InputTextModule,PasswordModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<main class="grid min-h-screen bg-canvas lg:grid-cols-[1.05fr_.95fr]">
 <section class="relative hidden overflow-hidden bg-forest p-12 text-white lg:flex lg:flex-col"><div class="flex items-center gap-3"><span class="flex size-11 items-center justify-center rounded-2xl bg-lime text-forest"><i class="pi pi-wave-pulse text-xl"></i></span><span class="text-xl font-bold">physiomotion<span class="text-lime">+</span></span></div><div class="my-auto max-w-xl"><p class="eyebrow text-lime">{{s.t('PHYSIO STUDIO','STUDIO PHYSIO')}}</p><h1 class="mt-5 text-5xl font-medium tracking-[-2px]">{{s.t('A calmer space for thoughtful care.','Un espace serein pour des soins attentifs.')}}</h1><p class="mt-6 max-w-md text-base leading-7 text-white/70">{{s.t('Manage modules, clients, and private conversations in one focused workspace.','Gérez les modules, les clients et les conversations privées dans un espace dédié.')}}</p></div><p class="text-xs text-white/55">© {{year}} Physiomotion Plus</p><div class="absolute -right-40 -bottom-40 size-[520px] rounded-full border border-white/10"></div></section>
 <section class="flex min-h-screen items-center justify-center px-5 py-10 sm:px-10"><div class="w-full max-w-md"><div class="mb-12 flex items-center justify-between"><span class="flex items-center gap-2 text-lg font-bold lg:hidden"><i class="pi pi-wave-pulse"></i> physiomotion<span class="-ml-2 text-sage">+</span></span><div class="flex rounded-full border border-line bg-white p-1"><button type="button" class="rounded-full px-3 py-1.5 text-xs font-semibold" [class.bg-forest]="!s.fr()" [class.text-white]="!s.fr()" (click)="s.fr.set(false)">EN</button><button type="button" class="rounded-full px-3 py-1.5 text-xs font-semibold" [class.bg-forest]="s.fr()" [class.text-white]="s.fr()" (click)="s.fr.set(true)">FR</button></div></div><p class="eyebrow">{{s.t('INVITATION ONLY','SUR INVITATION')}}</p><h2 class="mt-3 text-3xl font-medium tracking-tight">{{s.t('Sign in to Physio Studio','Accéder au Studio Physio')}}</h2><p class="mt-3 text-sm leading-6 text-muted">{{s.t('Use the account provided by your practice administrator.','Utilisez le compte fourni par votre administrateur de clinique.')}}</p>@if(error()){<p role="alert" class="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{error()}}</p>}@if(message()){<p role="status" class="mt-6 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-900">{{message()}}</p>}<form class="mt-7 space-y-5" (ngSubmit)="submit()"><label class="field"><span>{{s.t('Email address','Adresse courriel')}}</span><input pInputText name="email" type="email" autocomplete="email" [(ngModel)]="email" required /></label><label class="field"><span>{{s.t('Password','Mot de passe')}}</span><p-password name="password" [(ngModel)]="password" [toggleMask]="true" [feedback]="false" [fluid]="true" autocomplete="current-password" required /></label><button pButton type="submit" class="w-full justify-center" [loading]="busy()" [disabled]="busy()||!email||!password"><span pButtonLabel>{{s.t('Sign in','Se connecter')}}</span></button></form><div class="my-6 flex items-center gap-4"><span class="h-px flex-1 bg-line"></span><span class="text-xs font-medium text-muted">{{s.t('OR','OU')}}</span><span class="h-px flex-1 bg-line"></span></div><button pButton outlined severity="secondary" type="button" class="w-full justify-center bg-white" [loading]="googleBusy()" [disabled]="busy()||googleBusy()" (click)="google()"><i class="pi pi-google"></i><span pButtonLabel>{{s.t('Continue with Google','Continuer avec Google')}}</span></button><button type="button" class="mt-6 block text-sm font-medium text-sage hover:text-forest" (click)="reset()">{{s.t('Forgot password?','Mot de passe oublié?')}}</button></div></section></main>`})
export class Login { readonly s=inject(Store);readonly auth=inject(AdminAuthService);readonly year=new Date().getFullYear();readonly busy=signal(false);readonly googleBusy=signal(false);readonly error=signal('');readonly message=signal('');email='';password='';
 async submit(){this.busy.set(true);this.error.set('');try{await this.auth.signIn(this.email,this.password);}catch(e){this.error.set(this.msg(e));}finally{this.busy.set(false);}}
 async google(){this.googleBusy.set(true);this.error.set('');try{await this.auth.signInWithGoogle();}catch(e){if(!(e instanceof FirebaseError&&e.code==='auth/popup-closed-by-user'))this.error.set(this.msg(e));}finally{this.googleBusy.set(false);}}
 async reset(){if(!this.email){this.error.set(this.s.t('Enter your email address first.','Entrez d’abord votre adresse courriel.'));return;}try{await this.auth.reset(this.email);this.message.set(this.s.t('Password reset email sent.','Courriel de réinitialisation envoyé.'));}catch(e){this.error.set(this.msg(e));}}
 private msg(e:unknown){if(!(e instanceof FirebaseError))return this.s.t('Something went wrong. Please try again.','Une erreur est survenue. Veuillez réessayer.');if(e.code==='auth/invalid-credential')return this.s.t('The email or password is incorrect.','L’adresse courriel ou le mot de passe est incorrect.');if(e.code==='auth/popup-blocked')return this.s.t('Allow popups to continue with Google.','Autorisez les fenêtres contextuelles pour continuer avec Google.');return e.message;}}
